const productos = [
    {
      title: "Laptop muy linda",
      code: "GEN1",
      description: "Laptop genérica",
      price: 1500,
      stock: 10,
      thumbnails: [],
      category: "Tecnología",
      status: true,
    },
    {
      title: "Auriculares muy lindos",
      code: "GEN2",
      description: "Auriculares genéricos",
      price: 200,
      stock: 0,
      thumbnails: [],
      category: "Tecnología",
      status: true,
    },
    {
      title: "Silla muy linda",
      code: "GEN3",
      description: "Silla genérica",
      price: 350,
      stock: 0,
      thumbnails: [],
      category: "Casa",
      status: true,
    },
    {
      title: "Teclado muy lindo",
      code: "GEN4",
      description: "Teclado genérico",
      price: 234,
      stock: 15,
      thumbnails: [],
      category: "Tecnología",
      status: true,
    },
    {
      title: "Smartphone muy lindo",
      code: "GEN5",
      description: "Teléfono genérico",
      price: 800,
      stock: 20,
      thumbnails: [],
      category: "Tecnología",
      status: true,
    },
    {
        title: "Camiseta muy linda",
        code: "GEN6",
        description: "Camiseta genérica",
        price: 333,
        stock: 0,
        thumbnails: [],
        category: "Ropa",
        status: true,
      },
      {
        title: "Pantalón muy lindo",
        code: "GEN7",
        description: "Pantalón genérico",
        price: 300,
        stock: 30,
        thumbnails: [],
        category: "Ropa",
        status: true,
      },
      {
        title: "Mochila muy linda",
        code: "GEN8",
        description: "Mochila genérica",
        price: 2520,
        stock: 203,
        thumbnails: [],
        category: "Accesorios",
        status: true,
      },
      {
        title: "Zapatillas casuales",
        code: "A45187",
        description: "Zapatillas cómodas para uso diario.",
        price: 950,
        stock: 15,
        thumbnails: [],
        category: "Accesorios",
        status: true,
      },
      {
        title: "Chaqueta impermeable",
        code: "R18712",
        description: "Chaqueta ligera y resistente al agua.",
        price: 300,
        stock: 10,
        thumbnails: [],
        category: "Ropa",
        status: true,
      },
      {
        title: "Camiseta NIKE",
        code: "R92810",
        description: "Camiseta marca NIKE, de buena calidad",
        price: 800,
        stock: 50,
        thumbnails: [],
        category: "Ropa",
        status: true,
      },
      {
        title: "Zapatillas PUMA",
        code: "A17109",
        description: "Zapatillas cómodas para uso en carretera.",
        price: 950,
        stock: 22,
        thumbnails: [],
        category: "Accesorios",
        status: true,
      },
      {
        title: "Silla de madera",
        code: "C89818",
        description: "Silla de madera muy cómoda",
        price: 300,
        stock: 222,
        thumbnails: [],
        category: "Casa",
        status: true,
      },
  ];
  